# JPEG,HEIC,HEIF to lossy AVIF / MP4 to lossy H.265 CRF23 24fps
# The AVIF image has similar quality and size compared to JXL but wider compatibility: zooming on the immich preview will show the original AVIF image on any browser, it's much easier to view or share the image with others
tasks:
  - name: lossy-jpg-to-avif
    command: avifenc -q 70 "{{.folder}}/{{.name}}.{{.extension}}" "{{.result_folder}}/{{.name}}.avif"
    extensions:
      - jpeg
      - jpg

# HEIC LivePhotos will lose the video
  - name: heic-to-avif
    command: ./convert.sh "{{.folder}}" "{{.name}}" "{{.extension}}" "{{.result_folder}}" avif
    extensions:
      - heic
      - heif

  - name: ffmpeg
    command: ffmpeg -i "{{.folder}}/{{.name}}.{{.extension}}" -c:v libx265 -crf 23 -filter:v fps=24 -c:a copy -preset fast -map_metadata 0 -tag:v hvc1 "{{.result_folder}}/{{.name}}.{{.extension}}"
    extensions:
      - mp4