# JPEG,HEIC,HEIF to lossy JPEG-XL / MP4 to lossy H.265 CRF23 60fps
# The JXL image can be converted to a high quality (NOT THE ORIGINAL) JPEG. Use IUO_DOWNLOAD_JPG_FROM_JXL env variable to do that automatically on download (must-have feature due to JXL poor compatibility)
tasks:
  - name: lossy-jpg-to-jxl
    command: cjxl --lossless_jpeg=0 -q 75 -e 7 "{{.folder}}/{{.name}}.{{.extension}}" "{{.result_folder}}/{{.name}}.jxl"
    min_filesize: 1048576
    extensions:
      - jpeg
      - jpg

  # HEIC LivePhotos will lose the video
  - name: heic-to-jxl
    command: ./heic_convert.sh "{{.folder}}" "{{.name}}" "{{.extension}}" "{{.result_folder}}" jxl
    min_filesize: 1048576
    extensions:
      - heic
      - heif

  - name: ffmpeg
    command: ffmpeg -noautorotate -i "{{.folder}}/{{.name}}.{{.extension}}" -c:v libx265 -crf 23 -filter:v fps=60 -c:a copy -preset fast -map_metadata 0 -movflags use_metadata_tags -tag:v hvc1 "{{.result_folder}}/{{.name}}.{{.extension}}"
    extensions:
      - mp4