# JPEG to Lossless JPEG-XL
tasks:
  - name: jpeg-xl
    command: cjxl --lossless_jpeg=1 {{.folder}}/{{.name}}.{{.extension}} {{.result_folder}}/{{.name}}-new.jxl
    extensions:
      - jpeg
      - jpg