# All file extensions supported by immich: https://github.com/immich-app/immich/blob/main/server/src/utils/mime-types.ts
tasks:
  - name: passthrough-images
    command: ""
    extensions:
      - 3fr
      - ari
      - arw
      - cap
      - cin
      - cr2
      - cr3
      - crw
      - dcr
      - dng
      - erf
      - fff
      - iiq
      - k25
      - kdc
      - mrw
      - nef
      - nrw
      - orf
      - ori
      - pef
      - psd
      - raf
      - raw
      - rw2
      - rwl
      - sr2
      - srf
      - srw
      - x3f
      - avif
      - bmp
      - gif
      - heic
      - heif
      - hif
      - insp
      - jp2
      - jpe
      - jpeg
      - jpg
      - jxl
      - png
      - svg
      - tif
      - tiff
      - webp

  - name: passthrough-videos
    command: ""
    extensions:
      - 3gp
      - 3gpp
      - avi
      - flv
      - insv
      - m2t
      - m2ts
      - m4v
      - mkv
      - mov
      - mp4
      - mpe
      - mpeg
      - mpg
      - mts
      - vob
      - webm
      - wmv